import { SiGithub, SiLinkedin } from "@icons-pack/react-simple-icons";

export const portfolioData = {
  name: "Hiram Hernández Peña",
  universityDegree: "Computer Science Engineer",
  summary:
    "I'm a software developer with a passion for creating functional digital experiences.",
  description:
    "I'm a full Stack developer with more than 4 years of professional experience in different fields of advanced cross-platform software development, object-oriented programming, design and implementation of web applications. Knowledge ambition, high capacity to work under pressure and I'm always eager to learn new technologies and techniques.",
  email: "hiramhernandezpena@gmail.com",
  address: "La Habana, Cuba",
  education: {
    degree: "Computer Science Engineer",
    university: "University of Informatics Sciences",
    city: "La Habana",
    country: "Cuba",
    date: "10/2015 - 06/2019,",
  },
  languages: {
    spanish: "Native or Bilingual Proficiency",
    english: "Professional Working Proficiency",
  },
  links: [
    {
      name: "Github",
      url: "https://github.com/hirammahandi",
      icon: SiGithub,
    },
    {
      name: "Linkedin",
      url: "https://www.linkedin.com/in/hiram-hernandez-peña-3a9881217",
      icon: SiLinkedin,
    },
  ],
  skills: [
    "HTML5",
    "CSS",
    "Javascript",
    "Typescript",
    "React",
    "NextJs",
    "NodeJs",
    "NestJs",
    "Express",
    "Redux",
    "Jest",
    "Supertest",
    "Vitest",
    "Storybook",
    "Mongoose",
    "Typeorm",
    "MaterialUI",
    "Bootstrap",
    "Tailwind",
    "PostgresSQL",
    "MongoDB",
    "Nx Monorepo",
    "Turborepo",
    "Eslint",
    "Git",
    "AWS Services",
    "Graphql",
    "Unit Tests",
    "Integration Tests",
    "E2E Tests",
    "Clean Architecture",
  ],
  workExperience: [
    {
      title: "Full Stack Developer",
      company: "Atomic Coders LLC",
      description:
        "Working on Typescript full cover projects, as a full stack engineer, using NextJS and React in the frontend, NestJS, Express and AWS (Lambda, Api Gateway, Dynamo, S3) for the backend and Graphql and Rest Full for web api design, using typescript as programming language. With planning and organization skills. Ability to work with the Redux pattern. With the ability to work with Docker for NodeJS projects. With the ability to test frontend applications, lambdas and another services with unit tests and e2e tests.",
    },
    {
      title: "Frontend Web Developer",
      company: "Beelders.io",
      description:
        "Working on a complete project in Typescript, as a frontend web developer, using NextJS and React as web framework, Bootstrap as ui framework and Redux Tool Kit as global state handler. Using AWS S3 service for hosting of images.",
    },
    {
      title: "Frontend Web Developer",
      company: "Chagod Software, Caribbean Passion",
      description:
        "Working on a complete project in Typescript, as a frontend web developer, using NextJS and React as web framework, Styled Component as ui framework, apollo client and graphql.",
    },
    {
      title: "Frontend Web Developer",
      company: "Cubamax",
      description:
        "Working on two projects in nextjs completely in typescript. The first project an administration dashboard and the second project a web application with different services among them an e-commerce, remittance services and topup services. For these projects I worked with the ui framework shadcn/ui and nextjs as react metaframework in its app-router version using all the advantages it offers.",
    },
  ],
  projects: [
    {
      title: "Todo App",
      description:
        "Todo App is a simple todo app that uses IndexedDB as a database",
      image: "/todo-app.png",
      url: "https://todo-app-index-db.vercel.app/",
      githubLink: "https://github.com/hirammahandi/todo-app-index-db",
    },
    {
      title: "Doctor Medical Office",
      description:
        "Doctor Medical Office is a medical office management system",
      image: "/doctor-medical-office.png",
      url: "https://doctor-medical-office.vercel.app/",
      githubLink: "https://github.com/hirammahandi/doctor-medical-office",
    },
  ],
};

export const cvData = {
  professionalInfo: {
    council: "FrontEnd Services",
    clan: "Software Engineering",
    office: "VASS Madrid",
    position: "Full Stack Developer",
  },
  summary:
    "Full Stack Developer with more than 5 years of professional experience in advanced cross-platform software development, object-oriented programming, and design and implementation of web applications. Driven by a passion for knowledge, with a high capacity to work under pressure.",
  vassExperience: [
    {
      company: "VASS",
      startDate: "12/2025",
      endDate: "Present",
      position: "Senior Frontend Developer & Tech Consultant",
      project: "ES-SB-Unicaja-Apoyo VASS-N4",
      activities: [
        "Incident resolution and front-end development tasks",
        "Implementation of patterns and architecture",
        "Technical consulting",
      ],
      technologies: [
        "TypeScript",
        "Node.js",
        "React",
        "Microfrontend (Module Federation)",
      ],
      workflow: ["Git", "Bitbucket"],
    },
    {
      company: "VASS",
      startDate: "04/2025",
      endDate: "11/2025",
      position: "Tech Lead Frontend & Tech Lead Backend (Node.js)",
      project: "ES-QuironSalud-FE - Quiron University",
      activities: [
        "Creation and integration of a BFF with Express.js to communicate the frontend with Moodle platform via webservice",
        "Implementation of SSO authentication",
        "Consumption of Moodle webservices via REST API",
      ],
      technologies: [
        "TypeScript",
        "Node.js",
        "Express.js",
        "Next.js",
        "React",
        "JavaScript",
      ],
      workflow: ["Git", "GitLab"],
    },
    {
      company: "VASS",
      startDate: "04/2025",
      endDate: "11/2025",
      position: "Tech Lead Frontend & Tech Lead Backend (Node.js)",
      project: "ES-UAX-DS-Core LMS / Procesos MIRAsturias",
      activities: [
        "Creation and integration of a BFF with Express.js to communicate the frontend with Moodle platform via webservice",
        "Implementation of SSO authentication",
        "Consumption of Moodle webservices via REST API",
      ],
      technologies: [
        "TypeScript",
        "Node.js",
        "Express.js",
        "Next.js",
        "React",
      ],
      workflow: ["Git", "GitLab"],
    },
    {
      company: "VASS",
      startDate: "01/2025",
      endDate: "08/2025",
      position: "Tech Lead Backend (Node.js)",
      project: "ES-HISPASAT_NUEVO-SOG-FRONTEND",
      activities: [
        "Creation and integration of a BFF with NestJS to communicate the frontend with Strapi",
        "Integration of Single Sign-On (SSO) authentication with Azure",
      ],
      technologies: ["TypeScript", "Node.js", "NestJS"],
      workflow: ["Git", "Bitbucket"],
    },
    {
      company: "VASS",
      startDate: "12/2024",
      endDate: "01/2025",
      position: "Frontend Developer",
      project: "Home Mi Iberia",
      activities: [
        "Creation and integration of animated and dynamic components",
        "Analysis, identification and resolution of errors in reusable components and client web environments",
        "Responsive design implementation",
        "Multi-device and multi-browser component verification",
        "Application of accessibility standards",
        "Mobile-first development implementation",
      ],
      technologies: ["TypeScript", "HTML5", "CSS", "React"],
      workflow: ["Git", "GitHub"],
    },
  ],
  previousExperience: [
    {
      company: "Atomic Coders LLC",
      startDate: "12/2021",
      endDate: "11/2024",
      position: "Full Stack Developer",
      activities: [
        "TypeScript full-coverage projects as Full Stack Engineer",
        "Next.js and React on the frontend",
        "NestJS, Express, and AWS (Lambda, API Gateway, DynamoDB, S3) on the backend",
        "Web API design with GraphQL and RESTful approaches",
        "Docker for Node.js projects",
        "Unit tests and E2E tests for frontend applications, Lambdas and other services",
      ],
      technologies: [
        "TypeScript",
        "React",
        "Next.js",
        "NestJS",
        "Express",
        "AWS",
        "GraphQL",
        "Redux",
        "Docker",
      ],
    },
    {
      company: "Beelders.io",
      startDate: "12/2022",
      endDate: "04/2024",
      position: "Frontend Web Developer",
      project: "Beelders",
      activities: [
        "TypeScript complete project as Frontend Web Developer",
        "Next.js and React as web framework",
        "Bootstrap as UI framework",
        "Redux Toolkit for global state management",
        "AWS S3 for image hosting",
      ],
      technologies: [
        "TypeScript",
        "React",
        "Next.js",
        "Bootstrap",
        "Redux Toolkit",
        "AWS S3",
      ],
    },
    {
      company: "Chagod Software, Caribbean Passion",
      startDate: "02/2022",
      endDate: "10/2022",
      position: "Frontend Web Developer",
      activities: [
        "TypeScript complete project as Frontend Web Developer",
        "Next.js and React as web framework",
        "Styled Components as UI framework",
        "Apollo Client for data management",
        "GraphQL for API communication",
      ],
      technologies: [
        "TypeScript",
        "React",
        "Next.js",
        "Styled Components",
        "Apollo Client",
        "GraphQL",
      ],
    },
  ],
  education: {
    degree: "Computer Science Engineer",
    institution: "University of Informatics Sciences",
    location: "Havana, Cuba",
    years: "2015 - 2019",
  },
  languages: [
    {
      language: "English",
      speaking: "B1",
      writing: "B1",
      certified: true,
    },
    {
      language: "Spanish",
      speaking: "Native",
      writing: "Native",
      certified: false,
    },
  ],
  technicalSkills: {
    frontend: [
      "HTML5",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Redux",
      "React Hook Form",
      "Yup",
      "Zod",
    ],
    uiFrameworks: [
      "Material UI",
      "Bootstrap",
      "Tailwind CSS",
      "Semantic UI",
      "NextUI",
      "Storybook",
      "Shadcn UI",
    ],
    backend: ["Node.js", "NestJS", "Express", "Mongoose", "TypeORM"],
    cloudDevops: [
      "AWS Lambda",
      "AWS API Gateway",
      "AWS DynamoDB",
      "AWS S3",
      "Git",
      "Nx Monorepo",
      "Turborepo",
      "ESLint",
    ],
    testing: [
      "Jest",
      "Supertest",
      "Vitest",
      "Unit Testing",
      "Integration Testing",
      "E2E Testing",
    ],
    apiData: ["GraphQL", "Apollo Client", "PostgreSQL", "MongoDB"],
    architecture: ["Clean Architecture", "Screaming Architecture", "SOLID Principles"],
  },
};
